### ISSUE TITLE
Automated Testing Fuzz Error (1/24/2017 10:25 AM)

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-black-box-study#35]
Second error seems to appear along with the first:

```
Error: Assertion failed: center should be a finite Vector2
    at window.assertions.assertFunction (http://phettest.colorado.edu/assert/js/assert.js:21:13)
    at Circle.setCenter (http://phettest.colorado.edu/scenery/js/nodes/Node.js?bust=1485279530255:2532:17)
    at Circle.set center [as center] (http://phettest.colorado.edu/scenery/js/nodes/Node.js?bust=1485279530255:2537:32)
    at Array.updateSolderNodePosition (http://phettest.colorado.edu/circuit-construction-kit-common/js/common/view/SolderNode.js?bust=1485279530255:52:29)
    at Emitter.emit2 (http://phettest.colorado.edu/axon/js/Emitter.js?bust=1485279530255:147:49)
    at Property._notifyObservers (http://phettest.colorado.edu/axon/js/Property.js?bust=1485279530255:176:29)
    at Property._setAndNotifyObservers (http://phettest.colorado.edu/axon/js/Property.js?bust=1485279530255:165:14)
    at Property.set (http://phettest.colorado.edu/axon/js/Property.js?bust=1485279530255:133:16)
    at CircuitNode.translateVertexGroup (http://phettest.colorado.edu/circuit-construction-kit-common/js/common/view/CircuitNode.js?bust=1485279530255:486:40)
    at CircuitNode.drag (http://phettest.colorado.edu/circuit-construction-kit-common/js/common/view/CircuitNode.js?bust=1485279530255:443:14)
```

```
Error: Assertion failed: point was not a number
    at window.assertions.assertFunction (http://phettest.colorado.edu/assert/js/assert.js:21:13)
    at http://phettest.colorado.edu/circuit-construction-kit-common/js/common/model/Electron.js?bust=1485279530255:54:19
    at Array.listener (http://phettest.colorado.edu/axon/js/Multilink.js?bust=1485279530255:40:18)
    at Emitter.emit2 (http://phettest.colorado.edu/axon/js/Emitter.js?bust=1485279530255:147:49)
    at Property._notifyObservers (http://phettest.colorado.edu/axon/js/Property.js?bust=1485279530255:176:29)
    at Property._setAndNotifyObservers (http://phettest.colorado.edu/axon/js/Property.js?bust=1485279530255:165:14)
    at Property.set (http://phettest.colorado.edu/axon/js/Property.js?bust=1485279530255:133:16)
    at ElectronPropagator.step (http://phettest.colorado.edu/circuit-construction-kit-common/js/common/model/ElectronPropagator.js?bust=1485279530255:138:58)
    at Circuit.step (http://phettest.colorado.edu/circuit-construction-kit-common/js/common/model/Circuit.js?bust=1485279530255:487:38)
    at BlackBoxSceneModel.step (http://phettest.colorado.edu/circuit-construction-kit-common/js/common/model/CircuitConstructionKitModel.js?bust=1485279530255:110:22)
```

**Comment by samreid** [comment]
Circuit Construction Kit: Black Box Study is currently passing 60 seconds of fuzzing, closing for now.
