### ISSUE TITLE
Automated testing issues

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/circuit-construction-kit-black-box-study#47]
Four different possibly-related fuzz issues (didn't see in other CCK-related runnables yet).

```
circuit-construction-kit-black-box-study : fuzz : require.js : run
Uncaught Error: Assertion failed: point was not a number
Error: Assertion failed: point was not a number
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1487038101606/assert/js/assert.js:21:13)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1487038101606/circuit-construction-kit-common/js/common/model/Electron.js?bust=1487038906936:63:19
    at Array.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1487038101606/axon/js/Multilink.js?bust=1487038906936:40:18)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1487038101606/axon/js/Emitter.js?bust=1487038906936:147:49)
    at BooleanProperty._notifyObservers (https://bayes.colorado.edu/continuous-testing/snapshot-1487038101606/axon/js/Property.js?bust=1487038906936:176:29)
    at BooleanProperty._setAndNotifyObservers (https://bayes.colorado.edu/continuous-testing/snapshot-1487038101606/axon/js/Property.js?bust=1487038906936:165:14)
    at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1487038101606/axon/js/Property.js?bust=1487038906936:133:16)
    at ElectronPropagator.step (https://bayes.colorado.edu/continuous-testing/snapshot-1487038101606/circuit-construction-kit-common/js/common/model/ElectronPropagator.js?bust=1487038906936:103:58)
    at Circuit.step (https://bayes.colorado.edu/continuous-testing/snapshot-1487038101606/circuit-construction-kit-common/js/common/model/Circuit.js?bust=1487038906936:514:38)
    at ExploreScreenModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1487038101606/circuit-construction-kit-common/js/common/model/CircuitConstructionKitModel.js?bust=1487038906936:120:22)
Approximately 2/13/2017, 8:08:21 PM
```

```
circuit-construction-kit-black-box-study : fuzz : built : run
Uncaught TypeError: Cannot set property 'startOffset' of null
TypeError: Cannot set property 'startOffset' of null
    at endDrag (https://bayes.colorado.edu/continuous-testing/snapshot-1487036252939/circuit-construction-kit-black-box-study/build/circuit-construction-kit-black-box-study_en.html?postMessageOnLoad&postMessageOnError&fuzzMouse:974:13953)
    at end (https://bayes.colorado.edu/continuous-testing/snapshot-1487036252939/circuit-construction-kit-black-box-study/build/circuit-construction-kit-black-box-study_en.html?postMessageOnLoad&postMessageOnError&fuzzMouse:973:30709)
    at endDrag (https://bayes.colorado.edu/continuous-testing/snapshot-1487036252939/circuit-construction-kit-black-box-study/build/circuit-construction-kit-black-box-study_en.html?postMessageOnLoad&postMessageOnError&fuzzMouse:970:1876)
    at e.disposeVertexNode (https://bayes.colorado.edu/continuous-testing/snapshot-1487036252939/circuit-construction-kit-black-box-study/build/circuit-construction-kit-black-box-study_en.html?postMessageOnLoad&postMessageOnError&fuzzMouse:973:31692)
    at e.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1487036252939/circuit-construction-kit-black-box-study/build/circuit-construction-kit-black-box-study_en.html?postMessageOnLoad&postMessageOnError&fuzzMouse:974:711)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1487036252939/circuit-construction-kit-black-box-study/build/circuit-construction-kit-black-box-study_en.html?postMessageOnLoad&postMessageOnError&fuzzMouse:974:6848)
    at e._fireItemRemoved (https://bayes.colorado.edu/continuous-testing/snapshot-1487036252939/circuit-construction-kit-black-box-study/build/circuit-construction-kit-black-box-study_en.html?postMessageOnLoad&postMessageOnError&fuzzMouse:955:13307)
    at e.remove (https://bayes.colorado.edu/continuous-testing/snapshot-1487036252939/circuit-construction-kit-black-box-study/build/circuit-construction-kit-black-box-study_en.html?postMessageOnLoad&postMessageOnError&fuzzMouse:955:13587)
    at e.remove (https://bayes.colorado.edu/continuous-testing/snapshot-1487036252939/circuit-construction-kit-black-box-study/build/circuit-construction-kit-black-box-study_en.html?postMessageOnLoad&postMessageOnError&fuzzMouse:958:14097)
    at e.dropCircuitElementNodeInToolbox (https://bayes.colorado.edu/continuous-testing/snapshot-1487036252939/circuit-construction-kit-black-box-study/build/circuit-construction-kit-black-box-study_en.html?postMessageOnLoad&postMessageOnError&fuzzMouse:978:31260)
Approximately 2/13/2017, 7:37:32 PM
```

```
circuit-construction-kit-black-box-study : fuzz : require.js : run
Uncaught Error: Assertion failed: center should be a finite Vector2
Error: Assertion failed: center should be a finite Vector2
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1487036252939/assert/js/assert.js:21:13)
    at Circle.setCenter (https://bayes.colorado.edu/continuous-testing/snapshot-1487036252939/scenery/js/nodes/Node.js?bust=1487036790179:2574:17)
    at Circle.set center [as center] (https://bayes.colorado.edu/continuous-testing/snapshot-1487036252939/scenery/js/nodes/Node.js?bust=1487036790179:2579:32)
    at Array.updateSolderNodePosition (https://bayes.colorado.edu/continuous-testing/snapshot-1487036252939/circuit-construction-kit-common/js/common/view/SolderNode.js?bust=1487036790179:52:29)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1487036252939/axon/js/Emitter.js?bust=1487036790179:147:49)
    at Property._notifyObservers (https://bayes.colorado.edu/continuous-testing/snapshot-1487036252939/axon/js/Property.js?bust=1487036790179:176:29)
    at Property._setAndNotifyObservers (https://bayes.colorado.edu/continuous-testing/snapshot-1487036252939/axon/js/Property.js?bust=1487036790179:165:14)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1487036252939/axon/js/Property.js?bust=1487036790179:133:16)
    at CircuitNode.translateVertexGroup (https://bayes.colorado.edu/continuous-testing/snapshot-1487036252939/circuit-construction-kit-common/js/common/view/CircuitNode.js?bust=1487036790179:486:40)
    at CircuitNode.drag (https://bayes.colorado.edu/continuous-testing/snapshot-1487036252939/circuit-construction-kit-common/js/common/view/CircuitNode.js?bust=1487036790179:443:14)
Approximately 2/13/2017, 7:37:32 PM
```

```
circuit-construction-kit-black-box-study : fuzz : built : run
Uncaught TypeError: Cannot read property 'width' of undefined
TypeError: Cannot read property 'width' of undefined
    at e.updateURL (https://bayes.colorado.edu/continuous-testing/snapshot-1487037500682/circuit-construction-kit-black-box-study/build/circuit-construction-kit-black-box-study_en.html?postMessageOnLoad&postMessageOnError&fuzzMouse:972:28159)
    at e.updateSVGSelf (https://bayes.colorado.edu/continuous-testing/snapshot-1487037500682/circuit-construction-kit-black-box-study/build/circuit-construction-kit-black-box-study_en.html?postMessageOnLoad&postMessageOnError&fuzzMouse:972:27409)
    at e.updateSVG (https://bayes.colorado.edu/continuous-testing/snapshot-1487037500682/circuit-construction-kit-black-box-study/build/circuit-construction-kit-black-box-study_en.html?postMessageOnLoad&postMessageOnError&fuzzMouse:966:27939)
    at e.update (https://bayes.colorado.edu/continuous-testing/snapshot-1487037500682/circuit-construction-kit-black-box-study/build/circuit-construction-kit-black-box-study_en.html?postMessageOnLoad&postMessageOnError&fuzzMouse:966:27879)
    at e.update (https://bayes.colorado.edu/continuous-testing/snapshot-1487037500682/circuit-construction-kit-black-box-study/build/circuit-construction-kit-black-box-study_en.html?postMessageOnLoad&postMessageOnError&fuzzMouse:981:6581)
    at e.update (https://bayes.colorado.edu/continuous-testing/snapshot-1487037500682/circuit-construction-kit-black-box-study/build/circuit-construction-kit-black-box-study_en.html?postMessageOnLoad&postMessageOnError&fuzzMouse:982:2594)
    at e.update (https://bayes.colorado.edu/continuous-testing/snapshot-1487037500682/circuit-construction-kit-black-box-study/build/circuit-construction-kit-black-box-study_en.html?postMessageOnLoad&postMessageOnError&fuzzMouse:981:8121)
    at e.update (https://bayes.colorado.edu/continuous-testing/snapshot-1487037500682/circuit-construction-kit-black-box-study/build/circuit-construction-kit-black-box-study_en.html?postMessageOnLoad&postMessageOnError&fuzzMouse:982:2594)
    at e.update (https://bayes.colorado.edu/continuous-testing/snapshot-1487037500682/circuit-construction-kit-black-box-study/build/circuit-construction-kit-black-box-study_en.html?postMessageOnLoad&postMessageOnError&fuzzMouse:981:8121)
    at e.update (https://bayes.colorado.edu/continuous-testing/snapshot-1487037500682/circuit-construction-kit-black-box-study/build/circuit-construction-kit-black-box-study_en.html?postMessageOnLoad&postMessageOnError&fuzzMouse:982:2594)
Approximately 2/13/2017, 7:58:20 PM
```

**Comment by samreid** [comment]
@phet-steele are you seeing problems like these?

**Comment by jonathanolson** [comment]
See https://bayes.colorado.edu/continuous-testing/aqua/html/continuous-report.html (bypass certificate error for now, no credentials are required). CCK varieties are fairly regularly failing fuzzing.

**Comment by phet-steele** [comment]
> See https://bayes.colorado.edu/continuous-testing/aqua/html/continuous-report.html (bypass certificate error for now, no credentials are required). CCK varieties are fairly regularly failing fuzzing.

What @jonathanolson said, yes I still occasionally see these errors.

**Comment by samreid** [comment]
Unassigning until we start working on this sim for production.

**Comment by jonathanolson** [comment]
More (different) failures:
```
circuit-construction-kit-black-box-study : fuzz : require.js : load
Uncaught TypeError: Cannot read property 'get' of undefined
TypeError: Cannot read property 'get' of undefined
    at updateCutButtonPosition (https://bayes.colorado.edu/continuous-testing/snapshot-1489638355900/circuit-construction-kit-common/js/common/view/VertexNode.js?bust=1489639365677:208:77)
    at updateVertexNodePosition (https://bayes.colorado.edu/continuous-testing/snapshot-1489638355900/circuit-construction-kit-common/js/common/view/VertexNode.js?bust=1489639365677:218:7)
    at Property.link (https://bayes.colorado.edu/continuous-testing/snapshot-1489638355900/axon/js/Property.js?bust=1489639365677:250:11)
    at new VertexNode (https://bayes.colorado.edu/continuous-testing/snapshot-1489638355900/circuit-construction-kit-common/js/common/view/VertexNode.js?bust=1489639365677:220:29)
    at addVertexNode (https://bayes.colorado.edu/continuous-testing/snapshot-1489638355900/circuit-construction-kit-common/js/common/view/CircuitNode.js?bust=1489639365677:143:24)
    at Array.forEach (native)
    at ObservableArray.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1489638355900/axon/js/ObservableArray.js?bust=1489639365677:305:27)
    at new CircuitNode (https://bayes.colorado.edu/continuous-testing/snapshot-1489638355900/circuit-construction-kit-common/js/common/view/CircuitNode.js?bust=1489639365677:171:22)
    at WarmUpSceneView.CircuitConstructionKitScreenView [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1489638355900/circuit-construction-kit-common/js/common/view/CircuitConstructionKitScreenView.js?bust=1489639365677:156:24)
    at WarmUpSceneView.BlackBoxSceneView [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1489638355900/circuit-construction-kit-black-box-study/js/blackbox/view/BlackBoxSceneView.js?bust=1489639365677:43:38)
Approximately 3/15/2017, 10:25:55 PM
```

Hopefully any phet-io deployed version isn't failing fuzz testing?

**Comment by phet-steele** [comment]
Bayes hasn't been reporting any of these for a long while, probably thanks to the cleanup in #62. Thanks @samreid.
