### ISSUE TITLE
CT Cannot add a listener to a disposed TinyEmitter

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-black-box-study#74]
```
circuit-construction-kit-black-box-study : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/circuit-construction-kit-black-box-study/circuit-construction-kit-black-box-study_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1596003502498%22%2C%22timestamp%22%3A1596015950527%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Cannot add a listener to a disposed TinyEmitter
Error: Assertion failed: Cannot add a listener to a disposed TinyEmitter
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/assert/js/assert.js:22:13)
at TinyEmitter.addListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/axon/js/TinyEmitter.js:82:15)
at Vector2Property.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/axon/js/Property.js:379:25)
at new CircuitElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/circuit-construction-kit-common/js/model/CircuitElement.js:151:32)
at new Wire (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/circuit-construction-kit-common/js/model/Wire.js:37:5)
at addWireStubs (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/circuit-construction-kit-black-box-study/js/blackbox/model/BlackBoxSceneModel.js:104:21)
at BlackBoxSceneModel.resetBlackBoxSceneModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/circuit-construction-kit-black-box-study/js/blackbox/model/BlackBoxSceneModel.js:248:7)
at BlackBoxSceneModel.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/circuit-construction-kit-black-box-study/js/blackbox/model/BlackBoxSceneModel.js:263:10)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/circuit-construction-kit-common/js/view/CCKCScreenView.js:207:17)
at ResetAllButton.options.listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/scenery-phet/js/buttons/ResetAllButton.js:62:5)
id: Bayes Chrome
Snapshot from 7/29/2020, 12:18:22 AM

----------------------------------

circuit-construction-kit-black-box-study : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/circuit-construction-kit-black-box-study/circuit-construction-kit-black-box-study_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1596003502498%22%2C%22timestamp%22%3A1596009527279%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Cannot add a listener to a disposed TinyEmitter
Error: Assertion failed: Cannot add a listener to a disposed TinyEmitter
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/assert/js/assert.js:22:13)
at TinyEmitter.addListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/axon/js/TinyEmitter.js:82:15)
at Vector2Property.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/axon/js/Property.js:379:25)
at new CircuitElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/circuit-construction-kit-common/js/model/CircuitElement.js:151:32)
at new Wire (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/circuit-construction-kit-common/js/model/Wire.js:37:5)
at addWireStubs (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/circuit-construction-kit-black-box-study/js/blackbox/model/BlackBoxSceneModel.js:104:21)
at BlackBoxSceneModel.resetBlackBoxSceneModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/circuit-construction-kit-black-box-study/js/blackbox/model/BlackBoxSceneModel.js:248:7)
at BlackBoxSceneModel.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/circuit-construction-kit-black-box-study/js/blackbox/model/BlackBoxSceneModel.js:263:10)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/circuit-construction-kit-common/js/view/CCKCScreenView.js:207:17)
at ResetAllButton.options.listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/scenery-phet/js/buttons/ResetAllButton.js:62:5)
id: Bayes Chrome
Snapshot from 7/29/2020, 12:18:22 AM

----------------------------------

circuit-construction-kit-black-box-study : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/circuit-construction-kit-black-box-study/circuit-construction-kit-black-box-study_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1596003502498%22%2C%22timestamp%22%3A1596024819775%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Cannot add a listener to a disposed TinyEmitter
Error: Assertion failed: Cannot add a listener to a disposed TinyEmitter
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/assert/js/assert.js:22:13)
at TinyEmitter.addListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/axon/js/TinyEmitter.js:82:15)
at Vector2Property.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/axon/js/Property.js:379:25)
at new CircuitElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/circuit-construction-kit-common/js/model/CircuitElement.js:151:32)
at new Wire (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/circuit-construction-kit-common/js/model/Wire.js:37:5)
at addWireStubs (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/circuit-construction-kit-black-box-study/js/blackbox/model/BlackBoxSceneModel.js:104:21)
at BlackBoxSceneModel.resetBlackBoxSceneModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/circuit-construction-kit-black-box-study/js/blackbox/model/BlackBoxSceneModel.js:248:7)
at BlackBoxSceneModel.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/circuit-construction-kit-black-box-study/js/blackbox/model/BlackBoxSceneModel.js:263:10)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/circuit-construction-kit-common/js/view/CCKCScreenView.js:207:17)
at ResetAllButton.options.listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596003502498/scenery-phet/js/buttons/ResetAllButton.js:62:5)
id: Bayes Chrome
Snapshot from 7/29/2020, 12:18:22 AM
```

**Comment by samreid** [comment]
I pushed a fix for this in https://github.com/phetsims/circuit-construction-kit-common/commit/cc9289d1140698e11acff356a8d4e73f6e255e68
