### ISSUE TITLE
CT spacing must be a finite number

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-black-box-study#75]
```
circuit-construction-kit-black-box-study : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604755274496/circuit-construction-kit-black-box-study/circuit-construction-kit-black-box-study_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1604755274496%22%2C%22timestamp%22%3A1604777705876%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: spacing must be a finite number
Error: Assertion failed: spacing must be a finite number
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604755274496/assert/js/assert.js:22:13)
at VBox.setSpacing (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604755274496/scenery/js/nodes/LayoutBox.js:335:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604755274496/circuit-construction-kit-common/js/view/CircuitElementToolbox.js:57:16
at Array.forEach (<anonymous>)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604755274496/circuit-construction-kit-common/js/view/CircuitElementToolbox.js:48:13
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604755274496/axon/js/TinyEmitter.js:71:18)
at EnumerationProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604755274496/axon/js/Property.js:280:25)
at EnumerationProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604755274496/axon/js/Property.js:178:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604755274496/sun/js/buttons/RectangularRadioButton.js:126:51
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1604755274496/axon/js/TinyEmitter.js:71:18)
id: Bayes Chrome
Snapshot from 11/7/2020, 6:21:14 AM
```

**Comment by samreid** [comment]
This has been clear for the last several columns, closing.
