### ISSUE TITLE
Assertion failed: tandem name should be view

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/circuit-construction-kit-black-box-study#76]
I hit this when I was testing all sims in aqua for another GitHub issue.  Not sure why it's not showing up in CT.

It looks like BlackBoxSceneView extends CCKCScreenView.  Besides the tandem error, that seems like a decision to reconsider.

```
circuit-construction-kit-black-box-study
Uncaught Error: Assertion failed: tandem name should be view
Error: Assertion failed: tandem name should be view
    at window.assertions.assertFunction (http://localhost/~cmalley/GitHub/assert/js/assert.js:25:13)
    at new ScreenView (http://localhost/~cmalley/GitHub/joist/js/ScreenView.js:75:17)
    at new CCKCScreenView (http://localhost/~cmalley/GitHub/circuit-construction-kit-common/js/view/CCKCScreenView.js:100:5)
    at new BlackBoxSceneView (http://localhost/~cmalley/GitHub/circuit-construction-kit-black-box-study/js/blackbox/view/BlackBoxSceneView.js:76:5)
    at new WarmUpSceneView (http://localhost/~cmalley/GitHub/circuit-construction-kit-black-box-study/js/blackbox/view/WarmUpSceneView.js:31:5)
    at http://localhost/~cmalley/GitHub/circuit-construction-kit-black-box-study/js/blackbox/view/BlackBoxScreenView.js:42:38
    at StringProperty.link (http://localhost/~cmalley/GitHub/axon/js/Property.js:401:5)
    at new BlackBoxScreenView (http://localhost/~cmalley/GitHub/circuit-construction-kit-black-box-study/js/blackbox/view/BlackBoxScreenView.js:31:39)
    at BlackBoxScreen.createView (http://localhost/~cmalley/GitHub/circuit-construction-kit-black-box-study/js/blackbox/BlackBoxScreen.js:50:16)
    at BlackBoxScreen.initializeView (http://localhost/~cmalley/GitHub/joist/js/Screen.js:253:23)
```

**Comment by samreid** [comment]
Fixed, thanks!  Closing.

**Comment by pixelzoom** [comment]
Reopening.  That's a workaround, not a fix.   And it ignores the root problem.  If ScreenView is intended to be used as a top-level component (which is my understanding, and another sim-specific problem here), then the 'view' tandem requirement and assertion failure makes sense. If it OK to use ScreenView as a subcomponent (which is how you've used it), then 'view' tandem name should be the default, not a requirement that fails an assertion.

**Comment by samreid** [comment]
I agree that proposed solution was a workaround.  A good long-term solution should be scheduled when we reinvest effort in this sim.

**Comment by pixelzoom** [comment]
Here are a few reasons why using ScreenView anywhere other than top-level is a bad idea, and why this should be addressed before publishing.

* ScreenView is clearly documented as "the view portion of the Screen".  It's not "a view portion", it is "the view portion". We expect there to be one per screen. 

* ScreenView doc indicates how it's used by PDOM. Again, there is expected to be one ScreenView per Screen, which creates all of that Screen's PDOM subcomponents. If you're creating multiple ScreenViews, then your Screen has multiple PDOM components. What's that going to break?

```
For the PDOM view, this type creates  the three organizing elements associated with each screen:
```

* Code like this in RewardNode assumes (rightly) that there is on ScreenView per screen. There may be other such cases. What will break when you have multiple ScreenViews per Screen?
```js
  /**
   * Finds the first parent that is a ScreenView so we can listen for its transform, see https://github.com/phetsims/vegas/issues/4
   * @returns {Node}
   * @private
   */
  getScreenView() {
    return this.getUniqueTrail( node => node instanceof ScreenView ).rootNode();
  }
```

**Comment by KatieWoe** [comment]
Showing up now in CT: 
```
circuit-construction-kit-black-box-study : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/circuit-construction-kit-black-box-study/circuit-construction-kit-black-box-study_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1616082139562%22%2C%22timestamp%22%3A1616085741070%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: tandem name should be view
Error: Assertion failed: tandem name should be view
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/assert/js/assert.js:25:13)
at new ScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/joist/js/ScreenView.js:75:17)
at new CCKCScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/circuit-construction-kit-common/js/view/CCKCScreenView.js:100:5)
at new BlackBoxSceneView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/circuit-construction-kit-black-box-study/js/blackbox/view/BlackBoxSceneView.js:76:5)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/circuit-construction-kit-black-box-study/js/blackbox/view/BlackBoxScreenView.js:52:38
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/axon/js/TinyEmitter.js:86:18)
at StringProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/axon/js/Property.js:294:25)
at StringProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/axon/js/Property.js:191:14)
at StringProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/axon/js/Property.js:364:32)
at ComboBoxListBox.Action.parameters.phetioPrivate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/sun/js/ComboBoxListBox.js:72:22)
id: Bayes Chrome
Snapshot from 3/18/2021, 9:42:19 AM

----------------------------------

circuit-construction-kit-black-box-study : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/circuit-construction-kit-black-box-study/circuit-construction-kit-black-box-study_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1616082139562%22%2C%22timestamp%22%3A1616087826717%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: tandem name should be view
Error: Assertion failed: tandem name should be view
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/assert/js/assert.js:25:13)
at new ScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/joist/js/ScreenView.js:75:17)
at new CCKCScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/circuit-construction-kit-common/js/view/CCKCScreenView.js:100:5)
at new BlackBoxSceneView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/circuit-construction-kit-black-box-study/js/blackbox/view/BlackBoxSceneView.js:76:5)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/circuit-construction-kit-black-box-study/js/blackbox/view/BlackBoxScreenView.js:52:38
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/axon/js/TinyEmitter.js:86:18)
at StringProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/axon/js/Property.js:294:25)
at StringProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/axon/js/Property.js:191:14)
at StringProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/axon/js/Property.js:364:32)
at ComboBoxListBox.Action.parameters.phetioPrivate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/sun/js/ComboBoxListBox.js:72:22)
id: Bayes Chrome
Snapshot from 3/18/2021, 9:42:19 AM
```

**Comment by samreid** [comment]
Fixed, closing
