### ISSUE TITLE
CT Cannot read properties of undefined (reading 'carouselScale')

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-black-box-study#77]
```
circuit-construction-kit-black-box-study : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671791632897/circuit-construction-kit-black-box-study/build/phet/circuit-construction-kit-black-box-study_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1671791632897%22%2C%22timestamp%22%3A1671795640370%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of undefined (reading 'carouselScale')
TypeError: Cannot read properties of undefined (reading 'carouselScale')
at new _V (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671791632897/circuit-construction-kit-black-box-study/build/phet/circuit-construction-kit-black-box-study_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1671791632897%22%2C%22timestamp%22%3A1671795640370%7D&fuzz&memoryLimit=1000:1066:2119589)
at new Av (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671791632897/circuit-construction-kit-black-box-study/build/phet/circuit-construction-kit-black-box-study_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1671791632897%22%2C%22timestamp%22%3A1671795640370%7D&fuzz&memoryLimit=1000:1066:2134549)
at Pv.name [as createView] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671791632897/circuit-construction-kit-black-box-study/build/phet/circuit-construction-kit-black-box-study_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1671791632897%22%2C%22timestamp%22%3A1671795640370%7D&fuzz&memoryLimit=1000:1066:2135020)
at Pv.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671791632897/circuit-construction-kit-black-box-study/build/phet/circuit-construction-kit-black-box-study_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1671791632897%22%2C%22timestamp%22%3A1671795640370%7D&fuzz&memoryLimit=1000:1066:1229526)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671791632897/circuit-construction-kit-black-box-study/build/phet/circuit-construction-kit-black-box-study_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1671791632897%22%2C%22timestamp%22%3A1671795640370%7D&fuzz&memoryLimit=1000:1066:1504910)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671791632897/circuit-construction-kit-black-box-study/build/phet/circuit-construction-kit-black-box-study_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1671791632897%22%2C%22timestamp%22%3A1671795640370%7D&fuzz&memoryLimit=1000:1066:1505053)
id: Bayes Puppeteer
Snapshot from 12/23/2022, 3:33:52 AM

----------------------------------

circuit-construction-kit-black-box-study : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671791632897/circuit-construction-kit-black-box-study/circuit-construction-kit-black-box-study_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1671791632897%22%2C%22timestamp%22%3A1671794155400%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Undefined not allowed for Node key: scale
Error: Assertion failed: Undefined not allowed for Node key: scale
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671791632897/assert/js/assert.js:28:13)
at assert (Node.ts:6280:16)
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671791632897/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671791632897/sherpa/lib/lodash-4.17.4.js:9359:14)
at each (Node.ts:6276:6)
at mutate (CircuitElementToolbox.ts:65:13)
at (CCKCScreenView.ts:217:33)
at (ExploreScreenView.js:47:4)
at (ExploreScreen.js:35:15)
at createView (Screen.ts:303:22)
id: Bayes Puppeteer
Snapshot from 12/23/2022, 3:33:52 AM

----------------------------------

circuit-construction-kit-black-box-study : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671791632897/circuit-construction-kit-black-box-study/circuit-construction-kit-black-box-study_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1671791632897%22%2C%22timestamp%22%3A1671793559192%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: Undefined not allowed for Node key: scale
Error: Assertion failed: Undefined not allowed for Node key: scale
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671791632897/assert/js/assert.js:28:13)
at assert (Node.ts:6280:16)
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671791632897/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671791632897/sherpa/lib/lodash-4.17.4.js:9359:14)
at each (Node.ts:6276:6)
at mutate (CircuitElementToolbox.ts:65:13)
at (CCKCScreenView.ts:217:33)
at (ExploreScreenView.js:47:4)
at (ExploreScreen.js:35:15)
at createView (Screen.ts:303:22)
id: Bayes Puppeteer
Snapshot from 12/23/2022, 3:33:52 AM

----------------------------------

circuit-construction-kit-black-box-study : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671791632897/circuit-construction-kit-black-box-study/circuit-construction-kit-black-box-study_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1671791632897%22%2C%22timestamp%22%3A1671793956962%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: Undefined not allowed for Node key: scale
Error: Assertion failed: Undefined not allowed for Node key: scale
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671791632897/assert/js/assert.js:28:13)
at assert (Node.ts:6280:16)
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671791632897/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671791632897/sherpa/lib/lodash-4.17.4.js:9359:14)
at each (Node.ts:6276:6)
at mutate (CircuitElementToolbox.ts:65:13)
at (CCKCScreenView.ts:217:33)
at (ExploreScreenView.js:47:4)
at (ExploreScreen.js:35:15)
at createView (Screen.ts:303:22)
id: Bayes Puppeteer
Snapshot from 12/23/2022, 3:33:52 AM

----------------------------------

circuit-construction-kit-black-box-study : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671791632897/circuit-construction-kit-black-box-study/circuit-construction-kit-black-box-study_en.html?continuousTest=%7B%22test%22%3A%5B%22circuit-construction-kit-black-box-study%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1671791632897%22%2C%22timestamp%22%3A1671793649831%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Undefined not allowed for Node key: scale
Error: Assertion failed: Undefined not allowed for Node key: scale
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671791632897/assert/js/assert.js:28:13)
at assert (Node.ts:6280:16)
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671791632897/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1671791632897/sherpa/lib/lodash-4.17.4.js:9359:14)
at each (Node.ts:6276:6)
at mutate (CircuitElementToolbox.ts:65:13)
at (CCKCScreenView.ts:217:33)
at (ExploreScreenView.js:47:4)
at (ExploreScreen.js:35:15)
at createView (Screen.ts:303:22)
id: Bayes Puppeteer
Snapshot from 12/23/2022, 3:33:52 AM
```

**Comment by samreid** [comment]
Fixed, closing.
